name: Terraform apply for GCP

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment:
      name: development
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v3
      - id: auth
        name: authenticate to GCP
        uses: google-github-actions/auth@v0.8.2
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.TF_PLAN_SERVICE_ACCOUNT }}
      - name: setup google-cloud-sdk
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      - name: init
        run: terraform init -no-color
      - name: apply
        id: apply
        run: terraform apply -no-color -auto-approve -input=false
